config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users , only:[:new , :create , :edit , :update , :show]
  resources :sessions , only:[:new , :create , :destroy]
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :favorites , only:[:create , :destroy ,:index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content , length:{maximum: 200}
  validates :picture , presence: true
  belongs_to :user
  has_many :favorites , dependent: :destroy
  has_many :favotite_users , through: :favorites , source: :user
  mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name , presence: true
  validates :email , presence: true , length: {maximum:100} ,
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i } , uniqueness: true
  before_validation(:email.downcase)
  has_secure_password
  validates :password , presence: true , length: {minimum:6}
  mount_uploader :icon, ImageUploader
  has_many :posts
  has_many :favorites , dependent: :destroy
  has_many :favotite_posts , through: :favorites , source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id:params[:post_id])
    redirect_back(fallback_location: request.url)
    flash[:success] = "#{favorite.post.user.name}さんの投稿をお気に入り登録しました。"
  end

  def destroy
    favorite = current_user.favorites.find_by(id:params[:id]).destroy
    redirect_back(fallback_location: request.url)
    flash[:warning] = "#{favorite.post.user.name}さんの投稿をお気に入り解除しました。"
  end

  def index
    @posts = current_user.favotite_posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post , only:[:edit, :update, :show, :destroy ,:check_user]
  before_action :check_user, only:[:edit, :update, :destroy]

  def index
    @posts = Post.all.order("updated_at DESC")
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:success] = "新規投稿しました。"
      # PostMailer.post_mail(@post).deliver 
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    render 'new' if @post.invalid?
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:info] = "投稿の編集をしました。"
      # PostMailer.post_mail(@post).deliver 
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @post.destroy
    flash[:danger] = "投稿を削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :picture, :picture_cache, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_user
    redirect_to posts_path if current_user.id !=  @post.user_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to posts_path
    end
  end

  def create
    @user = User.find_by(email:params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = 'ログインしました'
      redirect_to posts_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:info] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user , only:[:edit, :update ,:show ,:check_user]
  before_action :check_user , only:[:edit, :update]

  def new
    if logged_in?
      redirect_to posts_path
    elsif params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '会員登録しました'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end
  def update
    if @user.update(user_params)
      flash[:info] = 'プロフィールを更新しました'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :icon, :icon_cache, :content, :gender, :age)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_user
    redirect_to edit_user_path(current_user.id) if current_user.id !=  @user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def chose_new_or_edit
    if action_name == 'new' or  action_name == 'confirm'
      confirm_posts_path
    else
      post_path
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<div class="row">
  <% @posts.each do |post|%>
    <div class="col-md-3">
      <div class="post-list-area">

      <div class="row">
        <div class="col-md-6 text-left">
          <p><%= post.user.icon.url.nil? ? image_tag("default.png" ,class:"post-icon")  : image_tag(post.user.icon.url,class:"post-icon") %>
          投稿者：<%= post.user.name %></p>
        </div>
        <div class="col-md-6 text-right">
          <% if current_user.id != post.user.id %>
            <% @favorite = current_user.favorites.find_by(post_id: post.id)%>
            <% if @favorite.present?%>
              <%= link_to image_tag('like.png' , width:'20' , class:"icon") , favorite_path(id: @favorite.id) , method: :delete , data:{confirm: "解除してもよろしいですか？"} %>
            <% else %>
              <%= link_to image_tag('unlike.png' , width:'20' , class:"icon") , favorites_path(post_id: post.id) , method: :post%>
            <% end %>
          <% end %>
        </div>
      </div>
        <div class="text-center"><%= link_to image_tag(post.picture.url , width:'80%'), post_path(post.id) %></div>
      </div>
    </div>
    <% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ICloneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
      <div class="header-left">
        <%= link_to image_tag('logo.png'), new_session_path ,class:"logo_image" %>
      </div>
      <div class="header-right">
      <ul>
        <% if logged_in? %>
          <li><%= link_to "投稿" , new_post_path ,class:"btn btn-primary btn-lg"%></li>
          <li><%= link_to 'お気に入り一覧' , favorites_path(user_id: current_user.id) , method: :get,class:"btn btn-default btn-lg"%>
          <li><%= link_to "マイページ" , user_path(current_user.id) ,class:"btn btn-default btn-lg"%></li>
          <li><%= link_to "ログアウト" , session_path(current_user.id) ,
          method: :delete ,data:{confirm:"ログアウトしますがよろしいですか？"},class:"btn btn-danger btn-lg"%></li>
        <% else %>
          <li><%= link_to 'ログイン' , new_session_path ,class:"btn btn-default btn-lg"%></li>
          <li><%= link_to '会員登録' , new_user_path ,class:"btn btn-primary btn-lg"%></li>
        <% end %>
      </ul>
      </div>
</header>

  <body>
  <div class="container">
    <%= render partial: 'layouts/flash_messages' %>
    <%= yield %>
  </div>
      <footer>
      <p>© 2015-2019 Copyright .</p>
    </footer>
  </body>

</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explantion">
  <h2><%= pluralize(@post.errors.count , '件' )%>のエラーがあります</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-left">
    <%= form_with(model: @post, local: true, url: chose_new_or_edit, class:"form-border") do |f|%>

      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content %>
      </div>

      <div class="form-group">
        <%= f.label :picture%><br>

        <%= image_tag(@post.picture.url) if @post.picture && @post.picture.url %><br>
        <%= f.file_field :picture%>
      </div>
        <%= f.hidden_field :picture_cache %>

      <div class="text-right">
        <%= f.submit '登録',class:"btn btn-default btn-xs"%>
        <%= link_to '一覧へ' , posts_path,class:"btn btn-default btn-xs"%>
      </div>

    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/posts/confirm.html.erb
<h1>確認画面</h1>
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-left">
    <%= form_with(model:@post , local: true ,url: posts_path, class:"form-border") do |f|%>

    <div class="form-group">
      <%= f.label :content %>
      <pre class="confirm-text-area"><%= @post.content %></pre>
    </div>
    <div class="form-group">
      <%= f.label :picture %>
      <p><%= image_tag(@post.picture.url) if @post.picture && @post.picture.url %></p>
    </div>
      <%= f.hidden_field :content %>
      <%= f.hidden_field :picture %>
      <%= f.hidden_field :picture_cache %>

    <div class="text-right">
      <%= f.submit '登録',class:"btn btn-default btn-xs"%>
      <p class="btn btn-default btn-xs" onclick="btnClick();">戻る</p>
    </div>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>
<%= form_with(model:@post , local: true ,url: new_post_path ,method: 'get',class:"hidden_filed") do |f|%>

  <%= f.hidden_field :content %>
  <%= f.hidden_field :picture %>
  <%= f.hidden_field :picture_cache %>

  <%= f.submit '戻る' , name: 'back' ,id:"backBtn",class:"btn btn-default btn-xs"%>

<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<%= link_to '新規作成' , new_post_path %>

<% @posts.each do |post|%>
  <pre> <%= post.content%></pre>
  <%# <%= image_tag(post.picture.url) if post.picture && post.picture.url %> 
  <%= link_to image_tag(post.picture.url, width: '230'), post_path(post.id) %>
  <% if current_user.id != post.user.id %>
    <% @favorite = current_user.favorites.find_by(post_id: post.id)%>
      <% if @favorite.present?%>
        <%= link_to 'お気に入り解除' , favorite_path(id: @favorite.id) , method: :delete , data:{confirm: "解除してもよろしいですか？"} %>
      <% else %>
        <%= link_to 'お気に入り登録' , favorites_path(post_id: post.id) , method: :post%>
      <% end %>
  <% else %>
    <%= link_to '編集' , edit_post_path(post.id)%>
    <%= link_to '削除' , post_path(post.id) ,method: :delete , data:{confirm: "削除してもよろしいですか？"}%>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>新規作成</h1>

<%= render 'form'%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-left">
    <div class:"form-small">

      <div class="row post-show-area">
        <div class="col-md-6">
          <p><%= image_tag(@post.picture.url , width:'300') %></p>
        </div>
        <div class="col-md-6">
          <div class="post-show-top-area">
            <div class="text-left float-left-area">
              <p>投稿者：<%= @post.user.name %></p>
            </div>
            <div class="text-right">
              <% if current_user.id == @post.user_id%>
                <%= link_to image_tag('edit.png' , width:'15' , class:"icon") , edit_post_path(@post) %>
                <%= link_to image_tag('dust.png' , width:'15' , class:"icon") , post_path(@post.id) ,method: :delete ,data:{confirm:'削除しますがよろしいですか？'} %>
              <% else %>
                <% @favorite = current_user.favorites.find_by(post_id: @post.id)%>
                  <% if @favorite.present?%>
                    <%= link_to image_tag('like.png' , width:'20' , class:"icon") , favorite_path(id: @favorite.id) , method: :delete , data:{confirm: "解除してもよろしいですか？"} %>
                  <% else %>
                    <%= link_to image_tag('unlike.png' , width:'20' , class:"icon") , favorites_path(post_id: @post.id) , method: :post%>
                  <% end %>
              <% end %>
            </div>
          </div>

          <pre class="post-msg-area"><%= @post.content %></pre>
            <div class="text-right">
              <%= link_to '一覧へ', posts_path %>
            </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/users/_error.html.erb
 <% if @user.errors.any? %>
  <div id ="error_explantion">
  <p><%= pluralize(@user.errors.count , "件") %>のエラーがあります。<p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: "error" %>

<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-left">
    <%= form_with(model:@user , local: true , class:"form-border") do |f| %>

      <div class="form-group">
      <%= f.label :icon %><br>
      <%= image_tag(@user.icon.url,class:"mypage-icon") if @user.icon && @user.icon.url %>
      <%= f.file_field :icon %>
      <%= f.hidden_field :icon_cache%>
      </div>
      <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      </div>

      <div class="form-group">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
      </div>

      <div class="form-group">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
      </div>

      <div class="form-group">
      <%= f.label :gender %><br>
      <label><%= f.radio_button :gender, true  %> 男 </label>
      <label><%= f.radio_button :gender, false %> 女 </label>
      </div>

      <div class="form-group">
      <%= f.label :age %><br>
      <%= f.text_field :age %>
      </div>

      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class="text-right">
        <%= f.submit '更新',class:"btn btn-default btn-xs"%>
        <%= link_to '一覧へ', posts_path,class:"btn btn-default btn-xs"%>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<%= link_to '会員登録' , new_user_path%>

app/views/users/new.html.erb
<%= render partial: "error" %>

<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 text-left">
<%= form_with(model:@user , local: true, class:"form-small") do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email %>
  </div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </div>

  <%# <% f.file_field :icon ,value="default.png"%> 
<div class="text-center">
  <%= f.submit '会員登録' ,class:"btn btn-primary btn-md"%><br>
  <p class="small-text">アカウントをお持ちですか？ <%= link_to 'ログインする', new_session_path%></p>
</div>
<% end %>
  </div>
  <div class="col-md-3">
  </div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-2">
    <p><%= image_tag(@user.icon.url,class:"mypage-icon") %></p>
    <h2><%= @user.name %></h2>
  </div>
  <div class="col-md-4 text-left">
    <div class="form-group">
      <p>メールアドレス：<%= @user.email %></p>
    </div>
    <div class="form-group">
    <p>自己紹介：<pre><%= @user.content %></pre></p>
    </div>
    <div class="form-group">
    <p>性別：<%= @user.gender ? '男' : '女' %></p>
    </div>
    <div class="form-group">
    <p>年齢：<%= @user.age %>歳</p>
    </div>
      <div class="text-right">
      <% if current_user.id == @user.id%>
        <%= link_to '編集', edit_user_path(@user) ,class:"btn btn-default btn-xs"%> 
      <% end %>
      <%= link_to '一覧へ', posts_path ,class:"btn btn-default btn-xs"%>
   </div>
  <div class="col-md-3">
  </div>
</div>